server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/share?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    port: 587
    username: ottshareproject@gmail.com
    password: ndkmchxcpzlkgzlg
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true